services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    environment:
      - MINECRAFT_SERVER_PATH=/minecraft
    volumes:
      - ${MINECRAFT_SERVER_PATH}:/minecraft:ro

  nginx:
    build:
      context: ..
      dockerfile: nginx/Dockerfile
    restart: unless-stopped
    ports:
      - "8083:80"
    depends_on:
      - backend
